import { Inter, Lexend } from "next/font/google";

import "@/scss/main.scss";

const inter = Inter({ subsets: ["latin"] });

const lexend = Lexend({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lexend.className} `}>
        {children}
      </body>
    </html>
  );
}
